stages:
  - publish

publish_package:
  image: curlimages/curl:latest
  stage: publish
  variables:
    URL: "$CI_SERVER_PROTOCOL://$CI_SERVER_HOST:$CI_SERVER_PORT/api/v4/projects/$CI_PROJECT_ID/packages/composer?job_token=$CI_JOB_TOKEN"
  script:
    - echo $URL
    - version=$([[ -z "$CI_COMMIT_TAG" ]] && echo "branch=$CI_COMMIT_REF_NAME" || echo "tag=$CI_COMMIT_TAG")
    - echo $version
    - response=$(curl -w "\n%{http_code}" --data $version $URL)
    - code=$(echo "$response" | tail -n 1)
    - body=$(echo "$response" | head -n 1)
    - if [ $code -eq 201 ]; then
      echo "Package has been successfully published - Code $code - $body";
      else
      echo "Failed to publish package - Code $code - $body";
      exit 1;
      fi
