services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  LMS3\Lms3h5p\:
    resource: '../Classes/*'

  LMS3\Lms3h5p\Command\H5pConfigSettingCommand:
    tags:
      - name: 'console.command'
        command: 'h5p:configsetting'

  LMS3\Lms3h5p\Command\H5pCopyResourcesCommand:
    tags:
      - name: 'console.command'
        command: 'h5p:copyresources'
